ToDoList/src/app/ToDoList.WebUI/Models/ErrorViewModel.cs
using System;

namespace ToDoList.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoList/src/app/ToDoList.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ToDoList.WebUI.Models;

namespace ToDoList.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoList/src/app/ToDoList.WebUI/Controllers/TodoItemController.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace ToDoList.WebUI.Controllers
{
    public class TodoItemController : Controller
    {
        public IActionResult Index([FromQuery]Guid listId)
        {
            ViewBag.TodoListId = listId;
            return View();
        }

        public IActionResult Add([FromQuery]Guid listId)
        {
            ViewBag.TodoListId = listId;
            return View();
        }

        public IActionResult Edit([FromQuery]Guid listId, [FromQuery]Guid id)
        {
            ViewBag.TodoListId = listId;
            ViewBag.TodoItemId = id;
            return View();
        }
    }
}

ToDoList/src/app/ToDoList.WebUI/Controllers/TodoListController.cs
using Microsoft.AspNetCore.Mvc;
using System;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ToDoList.WebUI.Controllers
{
    public class TodoListController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }

        public IActionResult Edit(Guid id)
        {
            ViewBag.TodoListId = id;
            return View();
        }
    }
}

ToDoList/src/app/ToDoList.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Anasayfa";
}

<div class="text-center">
    <h1 class="display-4">ToDoList'e Hoşgeldiniz</h1>
    <hr />
    <div class="text-left">
        <h5 class="display-8">ToDoList Kullanarak</h5>
        <ul>
            <li>Görev listeleri oluşturabilirsiniz.</li>
            <li>Görev listeleri için görevler oluşturabilirsiniz.</li>
            <li>Görevlere hatırlatmalar ekleyerek e-posta bildirimleri alabilirsiniz.</li>
        </ul>
    </div>
    <script>

        //getApi("/api/TodoList",
        //    function (response) { console.log("response => ", response); },
        //    function (error) { console.log("error => ", error); }
        //);

        //const todoLists = postApi("/api/TodoList", { firstName: "Burak" },
        //    function (response) { console.log("response => ", response); },
        //    function (error) { console.log("error => ", error); }
        //);
    </script>
</div>

ToDoList/src/app/ToDoList.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ToDoList - @ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="~/js/api-manager.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item user-anonymous">
                            <a class="nav-link text-dark" data-toggle="modal" data-target="#createUserModal">Kullanıcı Kayıt</a>
                        </li>
                        <li class="nav-item user-anonymous">
                            <a class="nav-link text-dark" data-toggle="modal" data-target="#loginUserModal">Kullanıcı Giriş</a>
                        </li>
                        <li class="nav-item user-authorized" style="display:none;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoList" asp-action="Index">Listelerim</a>
                        </li>
                    </ul>
                </div>
                <div class="nav-item user-authorized" style="display:none;">
                    <a href="javascript:void(0);" class="nav-link text-dark" id="userLogout">Hoşgeldiniz, Burak KIRBAĞ. [x]</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2018 - ToDoList
        </div>
    </footer>

    <div class="modal fade" id="loginUserModal" tabindex="-1" role="dialog" aria-labelledby="loginUserModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginUserModalLabel">Kullanıcı Girişi</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <label class="col-form-label">E-Posta Adresiniz</label>
                    <input type="email" id="loginUserEmail" name="loginUserEmail" class="form-control" />
                    <label class="col-form-label">Şifreniz</label>
                    <input type="password" id="loginUserPassword" name="loginUserPassword" class="form-control" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Vazgeç</button>
                    <a href="javascript:void(0);" class="btn btn-primary" id="btnUserLogin">Giriş Yap</a>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).on("click", "#btnUserLogin", function () {

            let userEmail = $('#loginUserEmail').val();
            let userPassword = $('#loginUserPassword').val();

            postApi("/api/Auth",
                { email: userEmail, password: userPassword },
                function (response) {
                    localStorage.setItem('user_token', response.data.token);
                    localStorage.setItem('user_firstName', response.data.firstName);
                    localStorage.setItem('user_lastName', response.data.lastName);
                    $("#loginUserModal").modal('hide');
                    $('.user-anonymous').css('display', 'none');
                    $('.user-authorized').css('display', 'block');
                },
                function (error) { }
            );
        });
    </script>

    <div class="modal fade" id="createUserModal" tabindex="-1" role="dialog" aria-labelledby="createUserModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createUserModalLabel">Kullanıcı Kayıt</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <label class="col-form-label">Adınız</label>
                    <input type="text" id="createUserFirstName" name="createUserFirstName" class="form-control" />
                    <label class="col-form-label">Soyadınız</label>
                    <input type="text" id="createUserLastName" name="createUserLastName" class="form-control" />
                    <label class="col-form-label">E-Posta Adresiniz</label>
                    <input type="email" id="createUserEmail" name="createUserEmail" class="form-control" />
                    <label class="col-form-label">Şifreniz</label>
                    <input type="password" id="createUserPassword" name="createUserPassword" class="form-control" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Vazgeç</button>
                    <a href="javascript:void(0);" class="btn btn-primary" id="btnUserCreate">Kayıt Ol</a>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).on("click", "#btnUserCreate", function () {

            let userFirstName = $('#createUserFirstName').val();
            let userLastName = $('#createUserLastName').val();
            let userEmail = $('#createUserEmail').val();
            let userPassword = $('#createUserPassword').val();

            postApi("/api/Account",
                { firstName: userFirstName, lastName: userLastName, email: userEmail, password: userPassword },
                function (response) {
                    localStorage.setItem('user_token', response.data.token);
                    localStorage.setItem('user_firstName', response.data.firstName);
                    localStorage.setItem('user_lastName', response.data.lastName);
                    $("#createUserModal").modal('hide');
                    $('.user-anonymous').css('display', 'none');
                    $('.user-authorized').css('display', 'block');
                    window.location = "/";
                },
                function (error) { }
            );
        });
    </script>

    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.min.js" type="text/javascript"></script>
    <script src="~/js/bootstrap-datetimepicker.min.js"></script>
    <link href="~/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    @RenderSection("Scripts", required: false)


</body>
</html>

ToDoList/src/app/ToDoList.WebUI/Views/TodoItem/Add.cshtml
@{
    ViewData["Title"] = "Yeni Görev Oluştur";
}

<div class="text-center">
    <h1 class="display-4">Görevlerim</h1>
    <hr />
    <div class="text-left">
        <h5 class="display-8">Yeni Görev Oluşturun</h5>

        <form>
            <div class="form-group">
                <label for="title">Başlık</label>
                <input type="text" class="form-control" id="title" placeholder="Başlık">
            </div>
            <div class="form-group">
                <label for="description">Not</label>
                <textarea class="form-control" id="note" rows="3"></textarea>
            </div>
            <div class="form-group">
                <label for="title">Bitiş Tarihi</label>
                <input type="text" class="form-control" id="dueDate" placeholder="Bitiş Tarihi">
            </div>
            <div class="form-group">
                <label for="title">Hatırlama Tarihi</label>
                <input type="text" class="form-control" id="reminderDate" placeholder="Hatırlama Tarihi">
            </div>
            <a href="javascript:void(0);" class="btn btn-primary" id="btnAdd">Ekle</a>
            <a class="btn btn-outline-info text-info" asp-area="" asp-controller="TodoItem" asp-action="Index" asp-route-listId="@ViewBag.TodoListId">Görevler Sayfasına Dön</a>
        </form>
    </div>
    <script>
        $(function () {
            $('#dueDate,#reminderDate').datetimepicker({
                format: 'DD.MM.YYYY HH:mm:ss'
            });
        });

        $('#btnAdd').on('click', function () {
            let title = $('#title').val();
            let note = $('#note').val();
            let dueDate = $('#dueDate').val();
            let reminderDate = $('#reminderDate').val();

            postApi("/api/TodoItem",
                { listId: "@ViewBag.TodoListId", title: title, note: note,dueDate:dueDate,reminderDate:reminderDate },
                function (response) { window.location = "/TodoItem?listId=@ViewBag.TodoListId"; },
                function (error) { console.log("error => ", error); }
            );
        });
    </script>
</div>

ToDoList/src/app/ToDoList.WebUI/Views/TodoItem/Edit.cshtml
@{
    ViewData["Title"] = "Görev Düzenle";
}

<div class="text-center">
    <h1 class="display-4">Görevlerim</h1>
    <hr />
    <div class="text-left">
        <h5 class="display-8">Görev Düzenleyin</h5>

        <form>
            <input type="hidden" id="id" />
            <div class="form-group">
                <label for="title">Başlık</label>
                <input type="text" class="form-control" id="title" placeholder="Başlık">
            </div>
            <div class="form-group">
                <label for="description">Not</label>
                <textarea class="form-control" id="note" rows="3"></textarea>
            </div>
            <div class="form-group">
                <label for="title">Bitiş Tarihi</label>
                <input type="text" class="form-control" id="dueDate" placeholder="Bitiş Tarihi">
            </div>
            <div class="form-group">
                <label for="title">Hatırlama Tarihi</label>
                <input type="text" class="form-control" id="reminderDate" placeholder="Hatırlama Tarihi">
            </div>
            <div class="form-group">
                <label for="title">Durumu</label>
                <select id="status" class="form-control">
                    <option value="Active">Aktif</option>
                    <option value="Completed">Tamamlandı</option>
                </select>
            </div>
            <a href="javascript:void(0);" class="btn btn-primary" id="btnUpdate">Kaydet</a>
            <a class="btn btn-outline-info text-info" asp-area="" asp-controller="TodoItem" asp-action="Index" asp-route-listId="@ViewBag.TodoListId">Görevler Sayfasına Dön</a>
        </form>
    </div>
    <script>
        $(function () {
            $('#dueDate,#reminderDate').datetimepicker({
                format: 'DD.MM.YYYY HH:mm:ss'
            });
        });

        getApi("/api/TodoItem/@ViewBag.TodoItemId",
                function (response) {
                    $('#id').val(response.data.todoItem.id);
                    $('#title').val(response.data.todoItem.title);
                    $('#note').val(response.data.todoItem.note);
                    $('#dueDate').val(response.data.todoItem.dueDate);
                    $('#reminderDate').val(response.data.todoItem.reminderDate);
                    $('#status option[value="' + response.data.todoItem.status+'"]').attr('selected', 'selected');
                },
                function (error) {  }
            );



        $('#btnUpdate').on('click', function () {
            let id = $('#id').val();
            let title = $('#title').val();
            let note = $('#note').val();
            let dueDate = $('#dueDate').val();
            let reminderDate = $('#reminderDate').val();
            let status = $('#status').val() == "Completed" ? 2 : 1;

            putApi("/api/TodoItem/@ViewBag.TodoItemId",
                { id: "@ViewBag.TodoItemId", title: title, note: note,dueDate:dueDate,reminderDate:reminderDate,status:status },
                function (response) { window.location = "/TodoItem?listId=@ViewBag.TodoListId"; },
                function (error) {  }
            );
        });
    </script>
</div>

ToDoList/src/app/ToDoList.WebUI/Views/TodoItem/Index.cshtml
@{
    ViewData["Title"] = "Listelerim";
}

<div class="text-center">
    <h1 class="display-4">Görevlerim</h1>
    <hr />
    <div class="text-left">
        <h4 class="display-8">Görevlerinizi Yönetin</h4>
        <a class="btn btn-outline-info text-info" asp-area="" asp-controller="TodoItem" asp-action="Index" asp-route-listId="@ViewBag.TodoListId">Yeniden Yükle</a>
        <a class="btn btn-outline-secondary text-dark" asp-area="" asp-controller="TodoItem" asp-action="Add" asp-route-listId="@ViewBag.TodoListId">Görev Oluştur</a>

        <div id="todoItems" class="row"></div>
    </div>
    <script>
        function getTodoItems() {
            getApi("/api/TodoItem?listId=@ViewBag.TodoListId",
                function (response) {
                    let todoItemInnerData = "";
                    if (response.data.todoItems && response.data.todoItems.length > 0) {
                    response.data.todoItems.forEach((item) => {
                        todoItemInnerData += '<div class="col-md-4 mt-3">';
                        todoItemInnerData += '<div class="card" style="width: 18rem;">';
                        todoItemInnerData += '<div class="card-body">';
                        if (item.status == "Active") {
                            todoItemInnerData += '<span class="badge badge-primary right">' + item.statusText + '</span>';
                        }
                        else {
                            todoItemInnerData += '<span class="badge badge-success right">' + item.statusText + '</span>';
                        }
                        todoItemInnerData += '<h5 class="card-title">' + item.title + '</h5>';
                        todoItemInnerData += '<p class="card-text">' + item.note + '</p>';
                        todoItemInnerData += '<div class="btn-group" role="group" aria-label="">';
                        todoItemInnerData += '<a href="/TodoItem/Edit?listId=@ViewBag.TodoListId&id=' + item.id + '" class="btn btn-outline-primary">Düzenle</a>';
                        todoItemInnerData += '<a href="javascript:void(0);" class="btn btn-outline-danger btnDelete" todoitem-id="' + item.id + '">Sil</a>';
                        todoItemInnerData += '</div>';
                        todoItemInnerData += '</div>';
                        todoItemInnerData += '</div>';
                        todoItemInnerData += '</div>';
                        });
                    }
                    $('#todoItems').empty();
                    $('#todoItems').wrapInner(todoItemInnerData);
                },
                function (error) { console.log("error => ", error); }
            );
        }

        getTodoItems();

        $(document).on("click", ".btnDelete", function () {
            let id = $(this).attr("todoitem-id");

            deleteApi("/api/TodoItem/" + id,
                function (response) {
                    getTodoItems();
                },
                function (error) { console.log("error => ", error); }
            );
        });

    </script>
</div>

ToDoList/src/app/ToDoList.WebUI/Views/TodoList/Add.cshtml
@{
    ViewData["Title"] = "Yeni Liste Oluştur";
}

<div class="text-center">
    <h1 class="display-4">Listelerim</h1>
    <hr />
    <div class="text-left">
        <h5 class="display-8">Yeni Liste Oluşturun</h5>

        <form>
            <div class="form-group">
                <label for="title">Başlık</label>
                <input type="text" class="form-control" id="title" placeholder="Başlık">
            </div>
            <div class="form-group">
                <label for="description">Açıklama</label>
                <textarea class="form-control" id="description" rows="3"></textarea>
            </div>
            <a href="javascript:void(0);" class="btn btn-primary" id="btnAdd">Ekle</a>
        </form>
    </div>
    <script>
        $('#btnAdd').on('click', function () {
            let title = $('#title').val();
            let description = $('#description').val();

            postApi("/api/TodoList",
                { title: title, description: description },
                function (response) { window.location = "/TodoList"; },
                function (error) { console.log("error => ", error); }
            );
        });
    </script>
</div>

ToDoList/src/app/ToDoList.WebUI/Views/TodoList/Edit.cshtml
@{
    ViewData["Title"] = "Liste Düzenle";
}

<div class="text-center">
    <h1 class="display-4">Listelerim</h1>
    <hr />
    <div class="text-left">
        <h5 class="display-8">Liste Düzenleyin</h5>

        <form>
            <input type="hidden" id="id" />
            <div class="form-group">
                <label for="title">Başlık</label>
                <input type="text" class="form-control" id="title" placeholder="Başlık">
            </div>
            <div class="form-group">
                <label for="description">Açıklama</label>
                <textarea class="form-control" id="description" rows="3"></textarea>
            </div>
            <div class="form-group">
                <label for="title">Durumu</label>
                <select id="status" class="form-control">
                    <option value="Active">Aktif</option>
                    <option value="Completed">Tamamlandı</option>
                </select>
            </div>
            <a href="javascript:void(0);" class="btn btn-primary" id="btnUpdate">Kaydet</a>
            <a class="btn btn-outline-info text-info" asp-area="" asp-controller="TodoList" asp-action="Index" asp-route-listId="@ViewBag.TodoListId">Görev Listesi Sayfasına Dön</a>
        </form>
    </div>
    <script>
        getApi("/api/TodoList/@ViewBag.TodoListId",
                function (response) {
                    $('#id').val(response.data.todoList.id);
                    $('#title').val(response.data.todoList.title);
                    $('#description').val(response.data.todoList.description);
                    $('#status option[value="' + response.data.todoList.status + '"]').attr('selected', 'selected');
                },
                function (error) {  }
            );



        $('#btnUpdate').on('click', function () {
            let id = $('#id').val();
            let title = $('#title').val();
            let description = $('#description').val();
            let status = $('#status').val() == "Completed" ? 2 : 1;

            putApi("/api/TodoList/@ViewBag.TodoListId",
                { id: "@ViewBag.TodoListId", title: title, description: description,status:status },
                function (response) { window.location = "/TodoList";},
                function (error) {  }
            );
        });
    </script>
</div>

ToDoList/src/app/ToDoList.WebUI/Views/TodoList/Index.cshtml
@{
    ViewData["Title"] = "Listelerim";
}

<div class="text-center">
    <h1 class="display-4">Listelerim</h1>
    <hr />
    <div class="text-left">
        <h4 class="display-8">Listelerinizi Yönetin</h4>
        <a class="btn btn-outline-info text-info" asp-area="" asp-controller="TodoList" asp-action="Index">Yeniden Yükle</a>
        <a class="btn btn-outline-secondary text-dark" asp-area="" asp-controller="TodoList" asp-action="Add">Liste Oluştur</a>

        <div id="todoLists" class="row"></div>
    </div>
    <script>
        function getTodoLists() {
            getApi("/api/TodoList",
                function (response) {
                    let todoListInnerData = "";
                    response.data.todoLists.forEach((list) => {
                        todoListInnerData += '<div class="col-md-4 mt-3">';
                        todoListInnerData += '<div class="card" style="width: 18rem;">';
                        todoListInnerData += '<div class="card-body">';
                        if (list.status == "Active") {
                            todoListInnerData += '<span class="badge badge-primary right">' + list.statusText + '</span>';
                        }
                        else {
                            todoListInnerData += '<span class="badge badge-success right">' + list.statusText + '</span>';
                        }
                        todoListInnerData += '<h5 class="card-title">' + list.title + '</h5>';
                        todoListInnerData += '<p class="card-text">' + list.description + '</p>';
                        todoListInnerData += '<div class="btn-group" role="group" aria-label="">';
                        todoListInnerData += '<a href="/TodoItem?listId=' + list.id + '" class="btn btn-outline-info">İncele</a>';
                        todoListInnerData += '<a href="/TodoList/Edit/' + list.id + '" class="btn btn-outline-primary">Düzenle</a>';
                        todoListInnerData += '<a href="javascript:void(0);" class="btn btn-outline-danger btnDelete" todolist-id="' + list.id + '">Sil</a>';
                        todoListInnerData += '</div>';
                        todoListInnerData += '</div>';
                        todoListInnerData += '</div>';
                        todoListInnerData += '</div>';
                    });
                    $('#todoLists').empty();
                    $('#todoLists').wrapInner(todoListInnerData);
                },
                function (error) { console.log("error => ", error); }
            );
        }

        getTodoLists();

        $(document).on("click", ".btnDelete", function () {
            let id = $(this).attr("todolist-id");

            deleteApi("/api/TodoList/" + id,
                function (response) {
                    getTodoLists();
                },
                function (error) { console.log("error => ", error); }
            );
        });

    </script>
</div>